import { memory, MemoryLayer, MemoryBus } from './memory';

export interface PolicyRecord {
  id: string;
  title: string;
  category: 'Legal' | 'Institutional' | 'Accreditation' | 'Academic';
  content: string;
  source: string;
  effectiveDate: string;
  nwuReference?: string;
  clauses?: { id: string; text: string }[];
}

/**
 * NWU Policy Memory V4.3
 * Implements strict compliance checking against verbatim 2024/2025 policies.
 */

class PolicyMemoryService {
  private lastUpdate: number = 0;
  private policies: PolicyRecord[] = [
    {
      id: 'nwu-ai-2025',
      title: 'NWU AI Policy (5P_5.10)',
      category: 'Institutional',
      content: 'Guidelines for the ethical use of Generative AI in research and teaching.',
      source: 'NWU Senate',
      effectiveDate: '2025-11-19',
      nwuReference: '5P_5.10',
      clauses: [
        { id: '5.1', text: 'The use of generative AI must be explicitly disclosed in all academic submissions.' },
        { id: '5.2', text: 'Students are responsible for the factual accuracy of all content, including AI-generated portions.' },
        { id: '5.3', text: 'Direct use of AI-generated text without substantial human transformation is prohibited.' },
        { id: '5.4', text: 'AI tools may only be used as supportive aids (e.g., grammar checking) unless otherwise stated.' }
      ]
    },
    {
      id: 'nwu-acad-int-2024',
      title: 'NWU Academic Integrity Policy',
      category: 'Academic',
      content: 'Core policy defining plagiarism and academic misconduct.',
      source: 'NWU Registrar',
      effectiveDate: '2024-11-01',
      clauses: [
        { id: '2.1', text: 'Plagiarism includes the failure to credit the use of AI tools as sources of information.' },
        { id: '2.2', text: 'Academic dishonesty encompasses any unauthorized use of technology to gain advantage.' },
        { id: '3.1', text: 'Fabrication or falsification of data using AI tools is a major disciplinary offense.' }
      ]
    }
  ];

  constructor() {
    // constructor side-effects removed to prevent circular dependency TDZ
  }

  getPolicy(key: string): PolicyRecord | undefined {
    return this.policies.find(p => p.id === key || p.title.includes(key));
  }

  async refreshPolicies() {
    this.lastUpdate = Date.now();
    memory.write(MemoryLayer.L0, "nwu_policy_last_refresh", this.lastUpdate);
    memory.write(MemoryLayer.L0, "nwu_policy_data", this.policies);
    MemoryBus.publish('nwu-policy', { type: 'REFRESH', count: this.policies.length });
  }

  getAllPolicies(): PolicyRecord[] {
    return this.policies;
  }
}

export class PolicyChecker {
  static checkText(text: string) {
    const findings: { violations: string[], warnings: string[], score: number } = {
      violations: [],
      warnings: [],
      score: 100
    };

    // 1. Disclosure Check
    const disclosureKeywords = ['ai used', 'generated by', 'ai was used', 'acknowledgment of ai'];
    if (!disclosureKeywords.some(k => text.toLowerCase().includes(k))) {
      findings.warnings.push("No explicit AI disclosure statement detected (NWU Clause 5.1 violation risk).");
      findings.score -= 10;
    }

    // 2. Acceptance Language Check
    const passiveAcceptance = ['it is generally accepted that ai', 'ai ensures that'];
    if (passiveAcceptance.some(k => text.toLowerCase().includes(k))) {
      findings.warnings.push("Detected passive AI acceptance language (NWU Clause 5.3).");
      findings.score -= 5;
    }

    // 3. Vague Adverbs (Vale-style integration)
    const vagueAdverbs = ['very', 'extremely', 'really', 'actually', 'basically'];
    const matches = vagueAdverbs.filter(a => new RegExp(`\\b${a}\\b`, 'gi').test(text));
    if (matches.length > 5) {
      findings.violations.push(`Excessive use of vague adverbs (${matches.slice(0, 3).join(', ')}...) flagged as non-academic.`);
      findings.score -= 15;
    }

    // 4. Citation Density (crude)
    const citationPattern = /\(\w+,\s\d{4}\)/g;
    const citations = text.match(citationPattern) || [];
    if (citations.length < (text.length / 1000)) {
      findings.violations.push("Low citation density detected relative to academic length (NWU Academic Integrity risk).");
      findings.score -= 20;
    }

    findings.score = Math.max(0, findings.score);

    MemoryBus.publish('integrity-alerts', { type: 'POLICY_CHECK', findings });
    return findings;
  }
}

export const nwuPolicyMemory = new PolicyMemoryService();

